### ISSUE TITLE
Problem with installation on Mac OS X

### ISSUE THREAD

**Issue by delta25** [WojciechMula/aspell-python#11]
I am having the same issue that sizhky was having a couple months ago. 

I am trying to install aspell for Python 3 (on MacOS X 10.11), and have encountered an issue (the same one) using both pip and the manual installer (by cloning the git repo). I have already installed aspell using MacPorts (sudo port install aspell) as well as the english dictionary (sudo port install aspell-dict-en).

The error is obvious (aspell.h cannot be found), however I have no idea how to fix it.

![aspell-python_ _-bash_ _87x71](https://cloud.githubusercontent.com/assets/20166924/16379350/73d8ec90-3c71-11e6-81c3-6ea8eeaed068.png)

I have the necessary header file as shown below, and the path is in the PATH environment variable. I even created a symbolic link to the gcc location for good measure, but that didn't work.

![include](https://cloud.githubusercontent.com/assets/20166924/16379409/b7150e8a-3c71-11e6-8332-7942a73f64f8.png)

Any help would be greatly appreciated.

**Comment by WojciechMula** [comment]
Could you please check where exactly aspell files were installed? And then add the key include_dirs to the Extension definition, in setup.3.py:

```
module = Extension('aspell',
    libraries = ['aspell'],
    library_dirs = ['/usr/local/lib/'],
    include_dirs = ['your directory'],
    sources = ['aspell.c']
)
```

**Comment by delta25** [comment]
Worked like a charm, thanks for your help.

In case anybody encounters the same issue, I had installed aspell using MacPorts (sudo port install aspell) and had to include the dir '/opt/local/include', which is where the header file for aspell (aspell.h) was located.
Hence, my setup.3.py looks like this:

`module = Extension('aspell',
    libraries = ['aspell'],
    library_dirs = ['/usr/local/lib/'],
    include_dirs = ['/opt/local/include'],
    sources = ['aspell.c']
)`

**Comment by WojciechMula** [comment]
Thanks for checking my suggestion. I've commited fixes.

**Comment by acerock6** [comment]
Hi, can you please suggest a similar solution for Windows?

**Comment by WojciechMula** [comment]
@acerock6 Hi, could you please provide the paths where aspell is installed on Windows? Please also open a new issue, as it's related to another OS.

**Comment by amadanmath** [comment]
As a note — I just had a similar issue (with Python3, pip, Homebrew). If anyone else has the same problem in the same environment, I resolved it in this manner:

    pip install \
        --global-option build_ext \
        --global-option=-I$(brew --prefix aspell)/include \
        --global-option=-L$(brew --prefix aspell)/lib \
        aspell-python-py3
