### ISSUE TITLE
Aspell .suggest not reciprocal?

### ISSUE THREAD

**Issue by ndvbd** [WojciechMula/aspell-python#17]
When doing `.suggest('patients')`, I don't see `patience` in the list.
But when doing `.suggest('patience')`, I do see `patients` in the list.

Why isn't it reciprocal?``

**Comment by WojciechMula** [comment]
Sorry, don't have a clue how aspell implements its suggestion algorithm. It seems there are some heuristics which manifest in lack of symmetry you observed.

**Comment by ndvbd** [comment]
Posted an issue here: `https://github.com/GNUAspell/aspell/issues/589`

**Comment by WojciechMula** [comment]
@ndvbd OK, so I'm closing the issue.
