### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by sizhky** [WojciechMula/aspell-python#8]
Hi,

I'm unable to run the setup as the following error pops up. What am I missing?

![image](https://cloud.githubusercontent.com/assets/3656100/12969937/b495459c-d0ad-11e5-8c50-fa25c9849bf1.png)

**Comment by WojciechMula** [comment]
You don't have aspell headers installed.

**Comment by sizhky** [comment]
How to install them?? Do you know?

**Comment by WojciechMula** [comment]
I don't use Windows, so maybe it's not the best pointer. Please look at http://aspell.net/win32/, the section "Development" contains some headers and libraries. Read also http://aspell.net/win32/Readme-win32.txt -- it seems that is not so easy. (However, my friend somehow compiled the extension years ago.)

**Comment by WojciechMula** [comment]
@sizhky have you finally compiled the module? Can I close this issue?

**Comment by sizhky** [comment]
Yeah, no I didn't bother to compile.
I used a different tool to get my work done, so we can consider this issue closed.
